version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ../../../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/blog_database
      RAILS_ENV: development

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/blog_database
      RAILS_ENV: development
    command: bundle exec whenever --update-crontab --set environment=development